# Build from monorepo root so npm workspaces (@heart-and-hustle/shared) resolve.
# NEXT_PUBLIC_* must exist at `next build` — Railway injects service variables as build args when declared here.
FROM node:20-alpine
WORKDIR /app

ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ARG NEXT_PUBLIC_IOS_APP_STORE_URL
ARG NEXT_PUBLIC_ANDROID_PLAY_STORE_URL
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ENV NEXT_PUBLIC_IOS_APP_STORE_URL=$NEXT_PUBLIC_IOS_APP_STORE_URL
ENV NEXT_PUBLIC_ANDROID_PLAY_STORE_URL=$NEXT_PUBLIC_ANDROID_PLAY_STORE_URL

COPY . .
RUN npm ci && npm run build:web

ENV NODE_ENV=production
EXPOSE 3000

# Railway sets PORT; Next must listen there (default 3000 is wrong on Railway).
CMD ["sh", "-c", "exec npm run start -w web"]
